site_name: System building with Dyalog APL
repo_url: https://github.com/5jt/build.dyalog.com
repo_name: build.dyalog.com
nav:
  - Home: index.md
    
theme:
  favicon: 'img/favicon-32.png'
  logo: 'img/dyalog-white.svg'
  features:
    - content.tabs.link
    - navigation.sections
    - navigation.instant
  name: material

extra:
  version:
    provider: mike

extra_css:
  - style/main.css
  - style/admonition-ucmdhelp.css

plugins:
  - search

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
